apiVersion: v1
kind: Service
metadata:
  name: {{ include "rdf-forge.fullname" . }}-gateway
  labels:
    {{- include "rdf-forge.labels" . | nindent 4 }}
    component: gateway
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.gateway.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rdf-forge.selectorLabels" . | nindent 4 }}
    component: gateway
